//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_history
    {
        public int Id { get; set; }
        public string Sender { get; set; }
        public string message_text { get; set; }
        public Nullable<System.DateTime> time_and_date { get; set; }
    }
}
